local M = {
  "lukas-reineke/indent-blankline.nvim",
  main = "ibl",
  event = "BufReadPre",
  opts = {
    enabled = true,
    indent = {
      char = { "▏", "|", "¦", "┆", "┊" },
      highlight = {
        -- "Class",
        "function",
        -- "method",
        -- "block",
        -- "list_literal",
        -- "selector",
        -- "^if",
        -- "^table",
        -- "if_statement",
        -- "while",
        -- "for",
      },
    },
    exclude = {
      filetypes = {
        "startify",
        "dashboard",
        "dotooagenda",
        "log",
        "fugitive",
        "gitcommit",
        "packer",
        "vimwiki",
        "markdown",
        "json",
        "txt",
        "vista",
        "help",
        "todoist",
        "NvimTree",
        "neo-tree",
        "peekaboo",
        "git",
        "TelescopePrompt",
        "undotree",
        "flutterToolsOutline",
        "", -- for all buffers without a file type
      },
      buftypes = { "terminal", "nofile" },
    },
    scope = {
      enabled = true,
      show_start = true,
      highlight = {
        --   -- "Class",
        "function",
        --   -- "method",
        --   -- "block",
        --   "list_literal",
        --   "selector",
        --   "^if",
        --   "^table",
        --   "if_statement",
        --   "while",
        --   "for",
      },
    },
  },
}

return M
